directories:
  output: D:\Code\Electron\electron-jue-jin\release
  buildResources: build
  app: D:\Code\Electron\electron-jue-jin\dist
files:
  - filter:
      - '**'
extends: null
productName: JueJin
appId: com.juejin.desktop
asar: true
nsis:
  oneClick: true
  perMachine: true
  allowToChangeInstallationDirectory: false
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: juejinDesktop
publish:
  - provider: generic
    url: http://localhost:5500/
electronVersion: 28.1.4
